app = "tg-bot-xin710731"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "8080"
BOT_TOKEN = "8523227582:AAHPOGm5qoTqxSBUliQTewVaiwrvpuu3UVY"
ADMIN_IDS = "8000075268"   # ← 管理员 ID 正确放这里

[experimental]
auto_rollback = true

[[services]]
internal_port = 8080
protocol = "tcp"
auto_start_machines = true
auto_stop_machines = false     # ← 把这里改成 false
min_machines_running = 1       # 保持至少一台机器在线

[[services.ports]]
port = 8080
handlers = ["http"]
